export const allStages = [
  {
    dayName: "SÁB",
    date: "14.JUN",
    color: "blue",
    attractions: [
      { name: "TRIO PÉ DE SERRA", artist: "", time: "15:00", pole: "Polo do Cruzeiro" },
      { name: "FORRÓ RAIZ", artist: "", time: "17:30", pole: "Polo do Cruzeiro" },
      { name: "POETAS POPULARES", artist: "", time: "16:00", pole: "Polo da Poesia" },
      { name: "CORAL MUNICIPAL", artist: "", time: "15:00", pole: "Polo Gospel" },
      { name: "GERALDO AZEVEDO", artist: "GERALDO AZEVEDO", time: "20:00", pole: "Palco Principal" },
      { name: "PRISCILA SENNA", artist: "PRISCILA SENNA", time: "21:30", pole: "Palco Principal" },
      { name: "DESEJO DE MENINA", artist: "DESEJO DE MENINA", time: "23:00", pole: "Palco Principal" },
    ],
  },
  {
    dayName: "DOM",
    date: "15.JUN",
    color: "green",
    attractions: [
      { name: "ZABUMBA NOSSA SENHORA", artist: "", time: "15:00", pole: "Polo Cultural" },
      { name: "BANDA REGIONAL", artist: "", time: "17:00", pole: "Polo Cultural" },
      { name: "FESTIVAL DE COMIDAS TÍPICAS", artist: "", time: "16:00", pole: "Polo Gastronômico" },
      { name: "FLÁVIO JOSÉ", artist: "FLÁVIO JOSÉ", time: "20:00", pole: "Palco Principal" },
      { name: "DORGIVAL DANTAS", artist: "DORGIVAL DANTAS", time: "21:30", pole: "Palco Principal" },
      { name: "CIRO SANTOS", artist: "CIRO SANTOS", time: "23:00", pole: "Palco Principal" },
    ],
  },
  {
    dayName: "SEG",
    date: "16.JUN",
    color: "yellow",
    attractions: [
      { name: "QUADRILHA MATUTA", artist: "", time: "15:00", pole: "Polo das Quadrilhas" },
      { name: "QUADRILHA JUNINA ARRETADA", artist: "", time: "16:30", pole: "Polo das Quadrilhas" },
      { name: "QUADRILHA TRADIÇÃO", artist: "", time: "18:00", pole: "Polo das Quadrilhas" },
      { name: "QUADRILHA MATUTA", artist: "QUADRILHA MATUTA", time: "19:00", pole: "Arena das Quadrilhas" },
      { name: "QUADRILHA JUNINA ARRETADA", artist: "QUADRILHA JUNINA ARRETADA", time: "20:30", pole: "Arena das Quadrilhas" },
      { name: "QUADRILHA TRADIÇÃO", artist: "QUADRILHA TRADIÇÃO", time: "22:00", pole: "Arena das Quadrilhas" },
    ],
  },
  {
    dayName: "TER",
    date: "17.JUN",
    color: "red",
    attractions: [
      { name: "CANTORES GOSPEL", artist: "", time: "16:00", pole: "Polo Gospel" },
      { name: "SARAU DE POESIA", artist: "", time: "17:00", pole: "Polo da Poesia" },
      { name: "LÉO FOGUETE", artist: "LÉO FOGUETE", time: "20:00", pole: "Palco Principal" },
      { name: "JONAS ESTICADO", artist: "JONAS ESTICADO", time: "21:30", pole: "Palco Principal" },
      { name: "JOÃO VAQUEIRO", artist: "JOÃO VAQUEIRO", time: "23:00", pole: "Palco Principal" },
    ],
  },
  {
    dayName: "QUA",
    date: "18.JUN",
    color: "purple",
    attractions: [
      { name: "FEIRA DE ARTESANATO", artist: "", time: "15:00", pole: "Polo Cultural" },
      { name: "TRIO PÉ DE SERRA", artist: "", time: "16:00", pole: "Polo do Cruzeiro" },
      { name: "XAND AVIÃO", artist: "XAND AVIÃO", time: "20:00", pole: "Palco Principal" },
      { name: "PABLO", artist: "PABLO", time: "21:30", pole: "Palco Principal" },
      { name: "FORROZÃO CHACAL", artist: "FORROZÃO CHACAL", time: "23:00", pole: "Palco Principal" },
    ],
  },
  {
    dayName: "QUI",
    date: "19.JUN",
    color: "orange",
    attractions: [
      { name: "FEIRA DE ARTESANATO", artist: "", time: "15:00", pole: "Polo Cultural" },
      { name: "CORAL INFANTIL", artist: "", time: "16:00", pole: "Polo Gospel" },
      { name: "MARA PAVANELLY", artist: "MARA PAVANELLY", time: "20:00", pole: "Palco Principal" },
      { name: "NATTAN", artist: "NATTAN", time: "21:30", pole: "Palco Principal" },
      { name: "JÚNIOR VIANNA", artist: "JÚNIOR VIANNA", time: "23:00", pole: "Palco Principal" },
    ],
  },
  {
    dayName: "SEX",
    date: "20.JUN",
    color: "cyan",
    attractions: [
      { name: "CONTAÇÃO DE HISTÓRIAS", artist: "", time: "14:00", pole: "Polo da Poesia" },
      { name: "TRIO NORDESTINO", artist: "TRIO NORDESTINO", time: "20:00", pole: "Palco Principal" },
      { name: "TATY GIRL", artist: "TATY GIRL", time: "21:30", pole: "Palco Principal" },
      { name: "ZEZO", artist: "ZEZO", time: "23:00", pole: "Palco Principal" },
    ],
  },
  {
    dayName: "SÁB",
    date: "21.JUN",
    color: "pink",
    attractions: [
      { name: "MOSTRA DE DANÇA", artist: "", time: "15:00", pole: "Polo Cultural" },
      { name: "IGOR KANNÁRIO", artist: "IGOR KANNÁRIO", time: "20:00", pole: "Palco Principal" },
      { name: "LIMÃO COM MEL", artist: "LIMÃO COM MEL", time: "21:30", pole: "Palco Principal" },
      { name: "MANO WALTER", artist: "MANO WALTER", time: "23:00", pole: "Palco Principal" },
    ],
  },
  {
    dayName: "DOM",
    date: "22.JUN",
    color: "lime",
    attractions: [
      { name: "CORAL JOVEM", artist: "", time: "14:00", pole: "Polo Gospel" },
      { name: "CÉSAR MENOTTI & FABIANO", artist: "CÉSAR MENOTTI & FABIANO", time: "20:00", pole: "Palco Principal" },
      { name: "AVINE VINNY", artist: "AVINE VINNY", time: "21:30", pole: "Palco Principal" },
      { name: "TARCÍSIO DO ACORDEON", artist: "TARCÍSIO DO ACORDEON", time: "23:00", pole: "Palco Principal" },
    ],
  },
  {
    dayName: "SEG",
    date: "23.JUN",
    color: "teal",
    attractions: [
      { name: "BATALHA DE RAP", artist: "", time: "16:00", pole: "Polo Cultural" },
      { name: "TOCA DO VALE", artist: "TOCA DO VALE", time: "20:00", pole: "Palco Principal" },
      { name: "SIMONE MENDES", artist: "SIMONE MENDES", time: "21:30", pole: "Palco Principal" },
      { name: "VITOR FERNANDES", artist: "VITOR FERNANDES", time: "23:00", pole: "Palco Principal" },
    ],
  },
  {
    dayName: "TER",
    date: "24.JUN",
    color: "brown",
    attractions: [
      { name: "LUIZ FIDELIS", artist: "LUIZ FIDELIS", time: "20:00", pole: "Palco Principal" },
      { name: "WALKYRIA SANTOS", artist: "WALKYRIA SANTOS", time: "21:30", pole: "Palco Principal" },
      { name: "BRUNO & MARRONE", artist: "BRUNO & MARRONE", time: "23:00", pole: "Palco Principal" },
    ],
  },
  {
    dayName: "SEX",
    date: "28.JUN",
    color: "black",
    attractions: [
      { name: "SHOW INFANTIL", artist: "", time: "15:00", pole: "Polo Cultural" },
      { name: "MAGNÍFICOS", artist: "MAGNÍFICOS", time: "20:00", pole: "Palco Principal" },
      { name: "BANDA CALYPSO", artist: "BANDA CALYPSO", time: "21:30", pole: "Palco Principal" },
      { name: "FELIPÃO", artist: "FELIPÃO", time: "23:00", pole: "Palco Principal" },
    ],
  },
];
